/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mcr;

import mcr.utils.SimpleTime;

public class App {

    public static void main(String[] args) {
        ControlPanel cp = new ControlPanel(3);
    }
}
